from qgis.PyQt.QtCore import Qt, QSettings, QSize
from qgis.PyQt.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QFormLayout,
    QTabWidget, QScrollArea, QComboBox, QLineEdit, QPushButton, QToolButton,
    QDoubleSpinBox, QSpinBox, QCheckBox, QLabel, QListWidget, QStyle, QSizePolicy, QSlider)
from qgis.core import QgsApplication, QgsMapLayerProxyModel
from qgis.gui import QgsMapLayerComboBox


def build_advanced_ui(d):
    root = QWidget()
    from .workbench_style import STYLE
    root.setObjectName('parcelWorkbench')
    root.setStyleSheet(STYLE)
    layout = QVBoxLayout(root)
    layout.setContentsMargins(12, 12, 12, 10)
    layout.setSpacing(8)
    d.setMinimumWidth(350)
    d.setWindowTitle('地块标注')
    title = QLabel('地块标注')
    title.setObjectName('brand')
    layout.addWidget(title)
    d.model_summary = QLabel()
    d.model_summary.setObjectName('model')
    d.model_summary.setWordWrap(True)
    layout.addWidget(d.model_summary)
    tabs = QTabWidget()
    tabs.setDocumentMode(True)
    layout.addWidget(tabs, 1)

    def page(title):
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        scroll.setFrameShape(QScrollArea.NoFrame)
        body = QWidget()
        body.setObjectName('page')
        content = QVBoxLayout(body)
        content.setContentsMargins(10, 6, 10, 12)
        content.setSpacing(10)
        scroll.setWidget(body)
        tabs.addTab(scroll, title)
        return content

    def section(container, title):
        label = QLabel(title)
        label.setProperty('section', True)
        container.addWidget(label)

    edit = page('标注')
    section(edit, '数据与类别')
    form = QFormLayout()
    form.setRowWrapPolicy(QFormLayout.WrapLongRows)
    form.setVerticalSpacing(9)
    edit.addLayout(form)
    d.raster_combo = QgsMapLayerComboBox()
    d.raster_combo.setFilters(QgsMapLayerProxyModel.RasterLayer)
    form.addRow('影像', d.raster_combo)
    d.vector_combo = QgsMapLayerComboBox()
    d.vector_combo.setFilters(QgsMapLayerProxyModel.PolygonLayer)
    d.vector_combo.setAllowEmptyLayer(True)
    form.addRow('输出图层', d.vector_combo)
    d.output_path = QLineEdit()
    d.output_path.setPlaceholderText('未选择保存路径')
    output = QHBoxLayout()
    output.addWidget(d.output_path)
    browse = QToolButton()
    browse.setIcon(root.style().standardIcon(QStyle.SP_DialogOpenButton))
    browse.setToolTip('新建或打开 Shapefile')
    browse.clicked.connect(d.choose_output_path)
    output.addWidget(browse)
    form.addRow('文件', output)
    d.category = QComboBox()
    d.category.setEditable(True)
    d.category.addItems(['cropland', 'background'])
    form.addRow('类别', d.category)

    def tool(row, name, icon, slot):
        button = QToolButton()
        graphic = QgsApplication.getThemeIcon(icon)
        if graphic.isNull():
            graphic = root.style().standardIcon(QStyle.SP_ArrowRight)
        button.setIcon(graphic)
        button.setIconSize(QSize(20, 20))
        button.setToolTip(name)
        button.setAccessibleName(name)
        button.setFixedSize(34, 34)
        button.clicked.connect(slot)
        row.addWidget(button)
        return button

    section(edit, '交互分割')
    row = QHBoxLayout()
    edit.addLayout(row)
    d.add_positive_btn = tool(row, '正点', '/mActionAdd.svg', lambda: d.canvas.setMapTool(d.positive_tool))
    d.add_negative_btn = tool(row, '负点', '/mActionRemove.svg', lambda: d.canvas.setMapTool(d.negative_tool))
    d.add_box_btn = tool(row, '框选', '/mActionSelectRectangle.svg', lambda: d.canvas.setMapTool(d.box_tool))
    d.clear_prompts_btn = tool(row, '清空提示', '/mActionDeleteSelected.svg', d.clear_prompts)
    row.addStretch()
    d.live_preview = QCheckBox('自动预览')
    d.live_preview.setChecked(True)
    d.prompt_label = QLabel()
    row = QHBoxLayout()
    row.addWidget(d.prompt_label)
    row.addStretch()
    row.addWidget(d.live_preview)
    edit.addLayout(row)
    row = QHBoxLayout()
    row.addWidget(QLabel('预览填充'))
    d.preview_opacity = QSlider(Qt.Horizontal)
    d.preview_opacity.setRange(0, 100)
    d.preview_opacity.setValue(27)
    d.preview_opacity.setAccessibleName('候选地块填充不透明度')
    row.addWidget(d.preview_opacity, 1)
    opacity_value = QLabel('27%')
    opacity_value.setFixedWidth(36)
    row.addWidget(opacity_value)
    d.preview_opacity.valueChanged.connect(lambda value: opacity_value.setText(f'{value}%'))
    d.preview_opacity.valueChanged.connect(d.update_preview_opacity)
    edit.addLayout(row)
    row = QHBoxLayout()
    edit.addLayout(row)
    for name, label, slot in [('predict_btn', '生成预览', d.predict_mask),
                              ('accept_btn', '确认地块', d.accept_preview),
                              ('reject_btn', '取消', d.reject_preview)]:
        button = QPushButton(label)
        button.setMinimumHeight(28)
        button.clicked.connect(slot)
        setattr(d, name, button)
        row.addWidget(button)
    d.accept_btn.setEnabled(False)
    d.accept_btn.setObjectName('primary')
    d.reject_btn.setEnabled(False)
    section(edit, '矢量修正')
    row = QHBoxLayout()
    row.setSpacing(4)
    edit.addLayout(row)
    tool(row, '选择地块', '/mActionSelectRectangle.svg', lambda: d.native_tool('actionSelect'))
    tool(row, '手工画面 · 右键完成', '/mActionAddPolygon.svg', lambda: d.native_tool('actionAddFeature'))
    tool(row, '顶点编辑', '/mActionVertexTool.svg', lambda: d.native_tool('actionVertexTool'))
    tool(row, '挖洞', '/mActionAddRing.svg', lambda: d.native_tool('actionAddRing'))
    tool(row, '重塑边界 · 削凸补凹', '/mActionReshape.svg', lambda: d.start_line_edit('trim'))
    d.split_btn = tool(row, '分割地块 · 保留两个地块', '/mActionSplitFeatures.svg', d.start_split)
    tool(row, '合并选中地块', '/mActionMergeFeatures.svg', d.merge_selected)
    tool(row, '删除选中地块', '/mActionDeleteSelected.svg', d.delete_selected)
    edit.addStretch()
    parcels = page('地块')
    d.parcel_count = QLabel('0 个地块')
    d.parcel_count.setProperty('section', True)
    parcels.addWidget(d.parcel_count)
    d.parcel_search = QLineEdit()
    d.parcel_search.setPlaceholderText('搜索编号或类别')
    d.parcel_search.setClearButtonEnabled(True)
    d.parcel_search.textChanged.connect(d.filter_parcels)
    parcels.addWidget(d.parcel_search)
    d.parcel_list = QListWidget()
    d.parcel_list.setMinimumHeight(110)
    d.parcel_list.setSelectionMode(QListWidget.ExtendedSelection)
    d.parcel_list.itemSelectionChanged.connect(d.select_parcels)
    d.parcel_list.itemDoubleClicked.connect(d.zoom_to_parcel)
    d.parcel_list.setToolTip('双击定位地块')
    parcels.addWidget(d.parcel_list, 1)
    row = QHBoxLayout()
    layout.addLayout(row)
    d.undo_btn = tool(row, '撤销未保存编辑', '/mActionUndo.svg', d.undo)
    d.redo_btn = tool(row, '重做', '/mActionRedo.svg', d.redo)
    d.save_btn = tool(row, '保存编辑（建立新撤销起点）', '/mActionSaveEdits.svg', d.save_layer)
    row.addStretch()

    settings = page('设置')
    section(settings, '推理引擎与保存')
    form = QFormLayout()
    form.setRowWrapPolicy(QFormLayout.WrapLongRows)
    settings.addLayout(form)
    d.backend_combo = QComboBox()
    d.backend_combo.addItems(['local', 'http', 'mock'])
    d.device_combo = QComboBox()
    d.device_combo.addItems(['cuda', 'cpu'])
    d.local_command, d.weights_path, d.service_url = QLineEdit(), QLineEdit(), QLineEdit()
    d.window_size = QSpinBox()
    d.window_size.setRange(512, 2048)
    d.window_size.setSingleStep(256)
    d.window_size.setValue(1024)
    d.simplify_tolerance, d.min_area = QDoubleSpinBox(), QDoubleSpinBox()
    for control in [d.simplify_tolerance, d.min_area]:
        control.setRange(0, 1000000000)
        control.setDecimals(4)
    for name, control in [('后端', d.backend_combo), ('设备', d.device_combo),
                          ('Python 命令', d.local_command), ('模型权重', d.weights_path),
                          ('服务地址', d.service_url), ('窗口像素', d.window_size),
                          ('简化容差', d.simplify_tolerance),
                          ('最小面积', d.min_area)]:
        form.addRow(name, control)
    d.simplify_tolerance.setToolTip('地图坐标单位')
    d.min_area.setToolTip('平方地图坐标单位')
    d.autosave = QCheckBox('定时保存 SHP')
    d.autosave.setToolTip('保存成功后 QGIS 原生撤销记录清空')
    d.save_interval = QSpinBox()
    d.save_interval.setRange(1, 60)
    d.save_interval.setSuffix(' 分钟')
    d.save_interval.setValue(5)
    form.addRow(d.autosave)
    form.addRow('保存间隔', d.save_interval)
    save = QPushButton('保存设置')
    save.clicked.connect(d.persist_settings)
    settings.addWidget(save)
    settings.addStretch()
    d.status_label = QLabel('就绪')
    d.status_label.setObjectName('status')
    d.status_label.setWordWrap(True)
    layout.addWidget(d.status_label)
    d.setWidget(root)
    for control in root.findChildren(QLineEdit) + root.findChildren(QComboBox):
        control.setMinimumWidth(0)
        control.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Fixed)
    d.update_prompt_label()
    d.mode_buttons = [(d.add_positive_btn, d.positive_tool),
                      (d.add_negative_btn, d.negative_tool),
                      (d.add_box_btn, d.box_tool), (d.split_btn, d.split_tool)]
    for button, _ in d.mode_buttons:
        button.setCheckable(True)
        button.clicked.connect(d.sync_tool_buttons)
    d.canvas.mapToolSet.connect(d.sync_tool_buttons)
    def engine_summary():
        from pathlib import Path
        backend = d.backend_combo.currentText()
        name = Path(d.weights_path.text()).stem if backend == 'local' else backend.upper()
        d.model_summary.setText(f'{name or "未选择模型"}  /  {d.device_combo.currentText().upper()}')
        d.local_command.setEnabled(backend == 'local')
        d.weights_path.setEnabled(backend == 'local')
        d.service_url.setEnabled(backend == 'http')
        d.weights_path.setToolTip(d.weights_path.text())
        d.local_command.setToolTip(d.local_command.text())
    for signal in [d.backend_combo.currentTextChanged, d.device_combo.currentTextChanged,
                   d.weights_path.textChanged, d.local_command.textChanged]:
        signal.connect(engine_summary)
    engine_summary()
